app/build.gradle
app/src/main/java/com/framgia/oleo/MainActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings.xml
autodimension.gradle
build.gradle
gradle.properties

- Description:
- Add library used in app
- Setting multi screen in app
- Build type version app debug - release
- Link remine: https://edu-redmine.framgia.vn/issues/5588

[Sprint 1] Task#5588 Init Library, Multi Screen, Build Type Version in App

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/local/UserLocalDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/local/dao/UserDao.kt
app/src/main/java/com/framgia/oleo/data/source/local/dao/UserDatabase.kt
app/src/main/java/com/framgia/oleo/data/source/model/User.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginViewModel.kt
app/src/main/java/com/framgia/oleo/utils/di/module/AppModule.kt
app/src/main/java/com/framgia/oleo/utils/di/module/RepositoryModule.kt
app/src/main/java/com/framgia/oleo/utils/extension/FragmentExt.kt

Save data user in Local
Link Redmine: https://edu-redmine.framgia.vn/issues/5914

Task#5914 save data in local

---

app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginViewModel.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/utils/extension/CheckValidate.kt
app/src/main/java/com/framgia/oleo/utils/extension/View.kt
app/src/main/res/layout/fragment_login.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Validate Phone number and Password in Login screen
- Check error when login with Google Account
Link Redmine: https://edu-redmine.framgia.vn/issues/5369

[Sprint2]Task#5369 validate phone number and email

---

app/src/main/java/com/framgia/oleo/screen/home/HomeFragment.kt

handle event when click item in menu
Link redmine: https://edu-redmine.framgia.vn/issues/5911

handle event when click item in menu

---

app/build.gradle
app/src/main/java/com/framgia/oleo/data/source/model/Message.kt
app/src/main/java/com/framgia/oleo/data/source/model/RoomChat.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapter.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt
app/src/main/java/com/framgia/oleo/utils/OnItemRecyclerViewClick.kt
app/src/main/java/com/framgia/oleo/utils/di/module/NetworkModule.kt
app/src/main/res/layout/adapter_message.xml
build.gradle

- Create database structure firebase database 
- Save data to firebase 
- Get list message form firebase
Link Redmine: https://edu-redmine.framgia.vn/issues/5913

Task#5913 get list message

---

app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/java/com/framgia/oleo/screen/signup/SignUpFragment.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt
app/src/main/java/com/framgia/oleo/utils/extension/CheckValidate.kt
app/src/main/res/layout/fragment_login.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

- Fix validate form Input phone number and password
Link redmine : https://edu-redmine.framgia.vn/issues/6080

[Sprint 2] Task#6080 Fix Validate Form Login

---

app/src/main/java/com/framgia/oleo/screen/setting/SettingFragment.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Handle event click Option in setting profile screen and logout account facebook & google
Link Redmine: https://edu-redmine.framgia.vn/issues/6452

handle event click in setting screen and logout account facebook & google

---

app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt

Fix bug when login with facebook account
Link Redmine: https://edu-redmine.framgia.vn/issues/6523

fix bug when login facebook account

---

app/build.gradle
app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginViewModel.kt
app/src/main/java/com/framgia/oleo/utils/di/module/NetworkModule.kt
gradle.properties

- fix bug login with google account
- link redmine : https://edu-redmine.framgia.vn/issues/6525

[Sprint 3]Task#6525 Fix Bug Login With Account Google

---

app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingFragment.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingViewModel.kt

Handle event logout when login with google account
Link Redmine: https://edu-redmine.framgia.vn/issues/6529

handle event logout when login with google account

---

app/build.gradle
app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

Login application with phone number
link redmine : https://edu-redmine.framgia.vn/issues/6513

Ref task 6513 login with phone number

---

app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/signup/SignUpFragment.kt
app/src/main/java/com/framgia/oleo/utils/extension/CheckValidate.kt
app/src/main/res/drawable/ic_close.xml
app/src/main/res/drawable/ic_tick.xml
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

Task: Fix Show Message SignUp & UI Sign Up Screen
+ Change case show message when signUp success
Redmine: https://edu-redmine.framgia.vn/issues/6353

[Sprint 3] Task#6353 Fix show message when signup

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/framgia/oleo/screen/setting/SettingFragment.kt
app/src/main/res/values/colors.xml

Get Location GPS User
Link Redmine: https://edu-redmine.framgia.vn/issues/6389

[Sprint 3] Task6389 Get Location GPS User

---

app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/res/layout/fragment_messages.xml
app/src/main/res/menu/menu.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

- Fix UI Message List
- Link Redmine: https://edu-redmine.framgia.vn/issues/6810

Task #6810: fix UI Message List

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/model/User.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/signup/SignUpFragment.kt
app/src/main/java/com/framgia/oleo/screen/signup/SignUpViewModel.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

link : https://edu-redmine.framgia.vn/issues/6807

[Sprint3] Task 6807 fix register with phone number

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/local/UserLocalDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginViewModel.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/main/MainViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingViewModel.kt
app/src/main/java/com/framgia/oleo/utils/extension/ActivityExt.kt
app/src/main/java/com/framgia/oleo/utils/extension/Common.kt

TasK : Fix Error Login 
- when tap item logout and login again, ui profile and home removed and not show
- when tap button back in home screen, login screen show => not show login screen when login success
- Automatically Login after the first login
Link redmine : https://edu-redmine.framgia.vn/issues/6760

[Sprint 3] Fix Error Login & Logout

---

app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt

- Fix get messsage data
- Link Redmine: https://edu-redmine.framgia.vn/issues/7222

Fix Get Message

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationAdapter.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationViewModel.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingViewModel.kt
app/src/main/res/layout/adapter_location.xml
app/src/main/res/layout/fragment_location.xml

Get list location from friend of user
Link redmine: https://edu-redmine.framgia.vn/issues/6978

sprint[3]task#6978 get list location from friend of user

---

app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/signup/SignUpFragment.kt
app/src/main/java/com/framgia/oleo/utils/extension/ActivityExt.kt
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/values/colors.xml

-Change DialogFragment to Fragment in SignUp Screen
-Link Redmine: https://edu-redmine.framgia.vn/issues/7424

Fix SignUp Screen

---

app/src/main/java/com/framgia/oleo/data/source/MessagesRepository.kt
app/src/main/java/com/framgia/oleo/data/source/MesssagesDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/remote/MesssagesRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapter.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapterViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/res/layout/adapter_message.xml
app/src/main/res/layout/fragment_boxchat.xml
app/src/main/res/layout/fragment_signup.xml

-Fix not show latest message and time
-Using live data in BoxChat ViewModel
-Link Redmine: https://edu-redmine.framgia.vn/issues/7141

[Sprint 3]Task#7141 Fix Not Show Latest Message

---

app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchFragment.kt

fix back button toolbar

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/framgia/oleo/data/service/LocationService.kt
app/src/main/java/com/framgia/oleo/data/service/RestartServiceLocation.kt
app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/home/HomeFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/main/MainViewModel.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingFragment.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingViewModel.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt
app/src/main/java/com/framgia/oleo/utils/extension/Common.kt

Task : Get Location In User
+ Run Service Get Location (10s) & auto start service when killed
+ Auto get Location in user
+ Checked network (change internet, on/offf internet)
+ Stop service when logout
+ Push information to sever when change location 
Link redmine : https://edu-redmine.framgia.vn/issues/7487

[Sprint 4] Run Service And Auto Get Location In Device

---

app/src/main/java/com/framgia/oleo/screen/follow/FollowListFragment.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowListViewModel.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowPagerAdapter.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedFragment.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedViewModel.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingFragment.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingViewModel.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingFragment.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingViewModel.kt
app/src/main/java/com/framgia/oleo/utils/di/module/FragmentBuildersModule.kt
app/src/main/java/com/framgia/oleo/utils/di/module/ViewModelModule.kt
app/src/main/res/layout/follow_list_fragment.xml
app/src/main/res/layout/followed_fragment.xml
app/src/main/res/layout/following_fragment.xml
app/src/main/res/layout/waiting_fragment.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

https://edu-redmine.framgia.vn/issues/6454

[Sprint 4] Task#6454 Create follow list screen

---

app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationAdapter.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationFragment.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationViewModel.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/res/layout/fragment_location.xml

- Show list user friend location
- Show user friend location on maps
- Redmine: https://edu-redmine.framgia.vn/issues/7488

[Sprint 4] show location on Google Maps

---

app/src/main/java/com/framgia/oleo/data/service/LocationService.kt

Task : Get Location User
Link redmine : https://edu-redmine.framgia.vn/issues/7487

Fix Error Push Location Conflict

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowListFragment.kt
app/src/main/java/com/framgia/oleo/screen/home/HomeFragment.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationFragment.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchFragment.kt
app/src/main/res/drawable/ic_clear.xml
app/src/main/res/layout/fragment_boxchat.xml
app/src/main/res/layout/fragment_location.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/fragment_setting.xml
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/layout/toolbar.xml

- Hiding keyboard when touch outside of the edittext
- Handle back event in LocationFragment, MessageOptionFragment
- Enable ViewPager swipe
- Adjust layout when keyboard show up.
Link: https://edu-redmine.framgia.vn/issues/8106

Fix Bug UI

---

app/src/main/java/com/framgia/oleo/screen/home/HomeFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Show dialog when user didn't allow permissions
- Fix crash app when hiding keyboard
Link: https://edu-redmine.framgia.vn/issues/8136

[Sprint 4] Task#8136 Show deny permission dialog

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowPagerAdapter.kt
app/src/main/java/com/framgia/oleo/screen/friendrequest/FriendRequestsFragment.kt
app/src/main/java/com/framgia/oleo/screen/friendrequest/FriendRequestsViewModel.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchAdapter.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchFragment.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchViewModel.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt

- Fix bug sent friend request to another user is already friend
- Fix bug sent friend request to yourself 
- Handle friend Request
- Add search user by name
- Link Redmine: https://edu-redmine.framgia.vn/issues/8103

[Sprint 4]Task #8103 Handle Friend Request

---

app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowListFragment.kt
app/src/main/java/com/framgia/oleo/screen/friendrequest/FriendRequestsFragment.kt
app/src/main/java/com/framgia/oleo/screen/friendrequest/FriendRequestsViewModel.kt
app/src/main/java/com/framgia/oleo/screen/location/LocationFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/OnMessageOptionListener.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchViewModel.kt
app/src/main/java/com/framgia/oleo/screen/setting/SettingFragment.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingAdapter.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingFragment.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingViewModel.kt
app/src/main/java/com/framgia/oleo/utils/di/module/ViewModelModule.kt
app/src/main/res/layout/adapter_waiting.xml
app/src/main/res/layout/fragment_option_message.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Send follow request for user Friend
- Accept waiting Follow request
- get all follow request of user
- Fix id textViewWatchList -> textViewLocationList
- Fix toolbar follow list screen
- Redmine: https://edu-redmine.framgia.vn/issues/6454

[Sprint 4] Task#6454 Get data for wating follow request

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/model/Followed.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowPagerAdapter.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingAdapter.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingFragment.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingViewModel.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingFragment.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingViewModel.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt
app/src/main/java/com/framgia/oleo/utils/di/module/FragmentBuildersModule.kt
app/src/main/java/com/framgia/oleo/utils/di/module/ViewModelModule.kt
app/src/main/res/drawable/button_block_bg.xml
app/src/main/res/layout/adapter_following.xml
app/src/main/res/layout/following_fragment.xml
app/src/main/res/layout/waiting_fragment.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- get data following screen
- add user who was followed
- fix name package: folowing , waiting screen
Redmine:https://edu-redmine.framgia.vn/issues/6455

Task 6454 get data following request

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedAdapter.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedFragment.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedViewModel.kt
app/src/main/res/drawable/button_unfollow_bg.xml
app/src/main/res/layout/adapter_followed.xml
app/src/main/res/layout/followed_fragment.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Handler unfollow event
- get all user who was followed
-redmine:https://edu-redmine.framgia.vn/issues/6454

[Sprint 4] Task#6454 Get data followed screen

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/model/FollowRequest.kt
app/src/main/java/com/framgia/oleo/data/source/model/Followed.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/follow/FollowListFragment.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedAdapter.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedFragment.kt
app/src/main/java/com/framgia/oleo/screen/followed/FollowedViewModel.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingAdapter.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingFragment.kt
app/src/main/java/com/framgia/oleo/screen/following/FollowingViewModel.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingAdapter.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingFragment.kt
app/src/main/java/com/framgia/oleo/screen/waiting/WaitingViewModel.kt
app/src/main/res/layout/adapter_followed.xml
app/src/main/res/layout/adapter_following.xml
app/src/main/res/layout/adapter_waiting.xml

- Fix NotifidatasetChange in recyclerView
- fix Followed and FollowRequest model
- fix query follow tree
Redmine: https://edu-redmine.framgia.vn/issues/6455

[Sprint 4] Task #6455 fix recyclerView followList Screen and fix query follow list

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/model/Friend.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsFragment.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsViewModel.kt
app/src/main/java/com/framgia/oleo/screen/friendrequest/FriendRequestsViewModel.kt
app/src/main/java/com/framgia/oleo/screen/home/HomeFragment.kt
app/src/main/java/com/framgia/oleo/utils/di/module/FragmentBuildersModule.kt
app/src/main/java/com/framgia/oleo/utils/di/module/ViewModelModule.kt
app/src/main/res/layout/fragment_contacts.xml

Task: Get List my friend user
Link redmine : https://edu-redmine.framgia.vn/issues/6443

[Sprint 4] Get List Contacts User

---

app/src/main/java/com/framgia/oleo/data/source/MessagesRepository.kt
app/src/main/java/com/framgia/oleo/data/source/MesssagesDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/model/BoxChat.kt
app/src/main/java/com/framgia/oleo/data/source/remote/MesssagesRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapter.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchAdapter.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchFragment.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchViewModel.kt

- Fix UI boxChat when click on EditText
- Change Model BoxChat use userFriendId for id
- Handle button message on search screen 
- Hide friend request button when user already friend 
-  Link Redmine: https://edu-redmine.framgia.vn/issues/8378

[Sprint 4]Handle button message on search screen

---

app/src/main/java/com/framgia/oleo/data/source/MessagesRepository.kt
app/src/main/java/com/framgia/oleo/data/source/MesssagesDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/remote/MesssagesRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt

- Fix crash app on messages screen

[Sprint 4] Fix Bug Messages Screen

---

app/src/main/java/com/framgia/oleo/screen/contacts/ContactsAdapter.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsFragment.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsViewModel.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ItemContactsViewModel.kt
app/src/main/res/layout/fragment_contacts.xml
app/src/main/res/layout/item_layout_contacts.xml
app/src/main/res/values/colors.xml

Task : As a user. I want to show list my friend
Link redmine : https://edu-redmine.framgia.vn/issues/6442

[Sprint 4] Create UI & Show Data Contacts

---

app/src/main/java/com/framgia/oleo/screen/contacts/ContactsFragment.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsViewModel.kt
app/src/main/res/layout/fragment_contacts.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Search friends in contact screen
- Link: https://edu-redmine.framgia.vn/issues/8409

[Sprint 4] Search contacts

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/forgotpassword/ForgotPasswordFragment.kt
app/src/main/java/com/framgia/oleo/screen/forgotpassword/ForgotPasswordViewModel.kt
app/src/main/java/com/framgia/oleo/screen/forgotpassword/ResetPasswordFragment.kt
app/src/main/java/com/framgia/oleo/screen/forgotpassword/ResetPasswordViewModel.kt
app/src/main/java/com/framgia/oleo/screen/login/LoginFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt
app/src/main/java/com/framgia/oleo/utils/di/module/FragmentBuildersModule.kt
app/src/main/java/com/framgia/oleo/utils/di/module/ViewModelModule.kt
app/src/main/java/com/framgia/oleo/utils/extension/CheckValidate.kt
app/src/main/res/color/resend_sms_code_state.xml
app/src/main/res/drawable/ic_success.xml
app/src/main/res/layout/fragment_forgot_password.xml
app/src/main/res/layout/fragment_reset_password.xml
app/src/main/res/layout/layout_reset_password_dialog.xml
app/src/main/res/layout/layout_verify_sms_code_dialog.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Verify phone number with sms 
- Reset password after verified
Link: https://edu-redmine.framgia.vn/issues/8137

[Sprint 5] Task #8137 Reset password with sms

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Check followRequest was send or not
- handler event when don't have permisson to see location list
Redmine: https://edu-redmine.framgia.vn/issues/6453

[Sprint 5] Task#6455 Fix option message screenn

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/res/layout/progress_dialog.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Fix ui opntion message screen
- Fix add follow request
Redmine: https://edu-redmine.framgia.vn/issues/6455

[Sprint 5] Task#6455 Fix option message

---

app/src/main/java/com/framgia/oleo/data/source/MessagesRepository.kt
app/src/main/java/com/framgia/oleo/data/source/MesssagesDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/MesssagesRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapter.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/java/com/framgia/oleo/utils/Constant.kt
app/src/main/res/layout/fragment_option_message.xml
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

Task: Update Nick Name Friend & Profile User
+ Update Nick Name For Friend
Link redmine : https://edu-redmine.framgia.vn/issues/8414

[Sprint 5] Update Nick Name Friend

---

app/src/main/java/com/framgia/oleo/data/source/MessagesRepository.kt
app/src/main/java/com/framgia/oleo/data/source/MesssagesDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/remote/MesssagesRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt
app/src/main/java/com/framgia/oleo/screen/home/HomeFragment.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapter.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapterViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesViewModel.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchFragment.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Handle event when click remove boxchat in Message Options Screen
- Fix bug when rename Boxchat
- Rename only Boxchat not Friend Name
- Link: https://edu-redmine.framgia.vn/issues/8488

[Sprint 5] Task#8488 Remove boxchat

---

app/src/main/java/com/framgia/oleo/data/source/model/Message.kt
app/src/main/java/com/framgia/oleo/data/source/remote/MesssagesRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatAdapter.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatFragment.kt
app/src/main/java/com/framgia/oleo/screen/boxchat/BoxChatViewModel.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsFragment.kt
app/src/main/java/com/framgia/oleo/screen/contacts/ContactsViewModel.kt
app/src/main/java/com/framgia/oleo/screen/main/MainActivity.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapter.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesAdapterViewModel.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessagesFragment.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchFragment.kt
app/src/main/java/com/framgia/oleo/screen/search/SearchViewModel.kt
app/src/main/java/com/framgia/oleo/utils/extension/Common.kt
app/src/main/res/drawable/ic_send_message.xml
app/src/main/res/layout/adapter_message.xml
app/src/main/res/layout/follow_list_fragment.xml
app/src/main/res/layout/fragment_boxchat.xml
app/src/main/res/layout/fragment_option_message_header.xml
app/src/main/res/layout/fragment_setting.xml
app/src/main/res/layout/friend_requests_fragment.xml

- Fix UI- UX BoxChat screen
- Change value time in Message to Long instead String
- Fix function Rename BoxChat 
- Link Redmine: https://edu-redmine.framgia.vn/issues/8413

[Sprint 5]Fix UI- UX BoxChat and Message Option Screen

---

app/src/main/java/com/framgia/oleo/data/source/UserDataSource.kt
app/src/main/java/com/framgia/oleo/data/source/UserRepository.kt
app/src/main/java/com/framgia/oleo/data/source/remote/UserRemoteDataSource.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionFragment.kt
app/src/main/java/com/framgia/oleo/screen/messages/MessageOptionViewModel.kt
app/src/main/res/values-vi-rVN/strings.xml
app/src/main/res/values/strings.xml

- Disable follow, add friend myselft
- Allow remove follow request, add friend request

Fix Add friend, Follow
